config/routes.rb
News::Application.routes.draw do
  resources :articles do
    member do
      get '/vote'=>"articles#vote"
       get '/my_articles'=>"articles#my_articles"
    end
  end
  resources :user_sessions

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/UserArticles.rb
class UserArticles < ActiveRecord::Base
  attr_accessible :user_id, :articles_id
end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :content, :rating, :title, :user_id
  belongs_to :user
  default_scope { order('rating DESC', 'created_at DESC') }
 validates_presence_of :content, :title, :message => "can't be empty"
end

app/models/user.rb
class User < ActiveRecord::Base

  authenticates_with_sorcery!
  attr_accessible :email, :password, :password_confirmation
  has_many :article

  validates_confirmation_of :password, :message => "should match confirmation", :if => :password

end

app/models/user_articles.rb
class UserArticles < ActiveRecord::Base
  attr_accessible :articles_id, :user_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :require_login

  def not_authenticated
    redirect_to login_path, :alert => "Please login first."
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_filter :require_login, :only => [:index, :show]
  before_filter :check_my_article, :only => [:delete, :edit, :create]
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  def my_articles
    @articles = Article.where(:user_id =>current_user.id)
    render :index
  end
  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])
    @user = User.find(@article.user_id)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end

  def check_my_article
    format.html { redirect_to :article, notice: "Not allowed." } unless params[:user_id]=session[:user_id]
  end

  def vote
    if current_user && UserArticles.where(:articles_id=>params[:id], :user_id=>current_user.id).count==0
      UserArticles.create(:articles_id=>params[:id], :user_id=>current_user.id)
      @articles=Article.find(params[:id])
      @articles.update_attributes(:rating => @articles.rating + 1)
    end
    respond_to do |format|
      format.js do
        render :js => "$('#vote#{params[:id]}').css('visibility', 'hidden');$('##{params[:id]}').html(parseInt($('##{params[:id]}').html())+1);"
      end
    end
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login, :except => [:destroy]
  def new
    @user = User.new
  end

  def create
    respond_to do |format|
      if @user = login(params[:email], params[:password])
        format.html { redirect_back_or_to(:articles, :notice => 'Login successful.') }
        format.xml { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { flash.now[:alert] = "Login failed."; render :action => "new" }
        format.xml { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    logout
    redirect_to(:login, :notice => 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
skip_before_filter :require_login, :only => [:index, :new, :create, :show, :activate, :login_from_http_basic]
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.slim
= form_for @article do |f|
  - if @article.errors.any?
    #error_explanation
      h2 = "#{pluralize(@article.errors.count, "error")} prohibited this article from being saved:"
      ul
        - @article.errors.full_messages.each do |message|
          li = message

  = f.hidden_field :user_id, {:value => session[:user_id]}
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :content
    = f.text_area :content

  .actions = f.submit 'Save'

app/views/articles/edit.html.slim
h1 Editing article

== render 'form'

= link_to 'Show', @article
'|
= link_to 'Back', articles_path

app/views/articles/index.html.slim
h1 News
br
-if current_user
  = link_to "Show only my articles", my_articles_article_path(0)
= link_to "Show all", articles_path

br

- @articles.each do |article|
  div
    h4 = article.title
    article = article.content
    p <b> Author: </b> #{article.user.email} (created_at: #{article.created_at.day}.#{article.created_at.month}.#{article.created_at.year})
    -if current_user && UserArticles.where(:articles_id => article.id, :user_id => session[:user_id]).count == 0
      p <b> Rating: </b><span id="#{article.id}">#{article.rating}</span> #{link_to "(Vote)", vote_article_path(article), {:remote=>true, :id => "vote"+article.id.to_s, :update => "index"}}
    -else
      p <b> Rating: </b><span id="#{article.id}">#{article.rating}</span>

    -if current_user && current_user = article.user_id
      p #{link_to 'Edit', edit_article_path(article)} #{link_to 'Destroy', article, :confirm => 'Are you sure?', :method => :delete}
    br
    br
br

= link_to 'New Article', new_article_path

app/views/articles/new.html.slim
h1 New article

== render 'form'

= link_to 'Back', articles_path

app/views/articles/show.html.slim
p
  strong User:
  = @user.email

  strong Title:
  = @article.title

  strong Content:
  article
    = @article.content
p
  strong Rating:
  = @article.rating
p
  strong Create date:
  = @article.create_date

-if current_user = @article.user_id
  = link_to 'Edit', edit_article_path(@article)
  '|
= link_to 'Back', articles_path

app/views/layouts/application.html.slim
DOCTYPE html
html
  head
    title News
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  body
    div class="navbar navbar-inverse"
      .navbar-inner
        .container
          = link_to "Test", articles_path, {:class=>"brand"}
          ul class="nav"
            li = link_to "Home", articles_path
            -if current_user
              li = link_to "Logout", :logout
            -else
              li = link_to "Login", :login


    .container
      div
        p id="notice" = notice
        p id="alert" = alert

      = yield

app/views/user_sessions/create.html.slim
h1 UserSessions#create
p Find me in app/views/user_sessions/create.html.slim

app/views/user_sessions/destroy.html.slim
h1 UserSessions#destroy
p Find me in app/views/user_sessions/destroy.html.slim

app/views/user_sessions/new.html.slim
h1 Login
= form_tag user_sessions_path, :method => :post do
  .field
    = label_tag :email
    br
    = email_field_tag :email
  .field
    = label_tag :password
    br
    = password_field_tag :password
  .actions
    = submit_tag "Login"

app/views/users/_form.html.slim
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :password
    = f.password_field :password
  .field
    = f.label :password_confirmation
    = f.password_field :password_confirmation
  .actions = f.submit 'Save'

app/views/users/edit.html.slim
h1 Editing user

== render 'form'

= link_to 'Show', @user
'|
= link_to 'Back', users_path

app/views/users/index.html.slim
h1 Listing users

table
  tr
    th
    th
    th

  - @users.each do |user|
    tr
      td = link_to 'Show', user
      td = link_to 'Edit', edit_user_path(user)
      td = link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New User', new_user_path

app/views/users/new.html.slim
h1 New user

== render 'form'

= link_to 'Back', users_path

app/views/users/show.html.slim
p#notice = notice


= link_to 'Edit', edit_user_path(@user)
'|
= link_to 'Back', users_path